#	Copyright 2009 Jeff R. Allen. All rights reserved.
#	Use of this source code is governed by a BSD-style
#	license that can be found in the LICENSE file of the Go
#	distribution.

include $(GOROOT)/src/Make.inc

TARG=goconserver
GOFILES=\
	server.go\

include $(GOROOT)/src/Make.cmd
